server:
  port: 8060


eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"

spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**

  main:
    web-application-type: reactive