spring:
  application:
    name: posts
  profiles:
    active: default
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/BlogDB
    password: root
  cloud:
    compatibility-verifier:
     enabled: false
    config:
      enabled: true
      uri: http://configserver:8088
      fail-fast: true
      retry:
        max-attempts: 5
        initial-interval: 5000
        multiplier: 1.5

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8081

