spring:
  application:
    name: configserver
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      enabled: true
      uri: http://configserver:8888
      fail-fast: true
      retry:
        max-attempts: 5
        initial-interval: 5000
        multiplier: 1.5
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    username: parallax717@gmail.com
    password: cdhv nwhl ncdz opwi
    port: '587'